### ISSUE TITLE
Swift 4 and Objective C

### ISSUE THREAD

**Issue by adrian-niculescu** [fromcelticpark/PHAssetResourceInputStream#6]
Since Swift 4 the method in `InputStream+PHAssetResourceInputStream.swift`
`public static func inputStream(withAssetResource assetResource: PHAssetResource) -> InputStream`
is not visible in Objective C. It has to explicitly be prefixed by `@objc`
The declaration would become
`@objc public static func inputStream(withAssetResource assetResource: PHAssetResource) -> InputStream`

Could you please make this change so that your code works from Objective C too.

**Comment by fromcelticpark** [comment]
@adrian-niculescu go ahead and check the new version  👌

**Comment by adrian-niculescu** [comment]
It works! Thank you!
